### ISSUE TITLE
CLI生成项目运行出错

### ISSUE THREAD

**Issue by meimosor** [hjfruit/react-native-lidong-template#3]
![image](https://user-images.githubusercontent.com/31975932/196091708-cff024ef-c2a1-4e67-93a6-60c290fb2749.png)
使用cli生成项目后，启动找不到MainActivity

**Comment by onlyling** [comment]
这个原因是因为 Android 多环境、渠道造成的，手动打开应用是不会有差别的。

如果想一气呵成可以修改 `package.json` 里面 `android` 的命令，把 `--variant` 的值改为 `productionDebug`。

在 `android/app/build.gradle` 文件的 `productFlavors ` 配置中对不同环境的 `applicationId` 添加了前缀，确保一个手机上可以同时安装多个环境的应用。如果开发中遇见 `applicationId` 的问题可以调整打包时的环境指定。

**Comment by meimosor** [comment]
> 
谢谢解答，我这边还遇到一个问题，在启动后访问报错：找不到资源路径
![image](https://user-images.githubusercontent.com/31975932/196102623-4b793a92-5481-40f2-8b95-4f1e64d4a127.png)
相关依赖都引入了：
`
"@babel/core": "^7.19.3",
    "@babel/runtime": "^7.19.4",
    "@react-native-community/eslint-config": "^2.0.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/color": "^3.0.3",
    "@types/crypto-js": "^4.1.1",
    "@types/jest": "^26.0.23",
    "@types/lodash": "^4.14.186",
    "@types/react-native": "^0.70.4",
    "@types/react-native-vector-icons": "^6.4.12",
    "@types/react-native-video": "^5.0.14",
    "@types/react-test-renderer": "^18.0.0",
    "@typescript-eslint/eslint-plugin": "^5.40.0",
    "@typescript-eslint/parser": "^5.40.0",
    "babel-plugin-module-resolver": "^4.1.0",
    "cross-env": "^7.0.3",
    "eslint": "^7.32.0",
    "metro-react-native-babel-preset": "^0.73.1",
    "prettier": "^2.7.1",
    "react-native-flipper": "^0.157.0",
    "react-native-mmkv-flipper-plugin": "^1.0.0",
    "react-test-renderer": "18.0.0",
    "typescript": "^4.8.4"
`

babel.config.js
`
const presets = ['module:metro-react-native-babel-preset'];
const plugins = [];

plugins.push(
  [
    'module-resolver',
    {
      root: ['./src'],
      alias: {
        '@': './src',
      },
    },
  ],
  'react-native-reanimated/plugin',
);

module.exports = {
  presets,
  plugins,
};
`
tsconfig:
`
{
  "extends": "./tsconfig.react-native.json",     /* Recommended React Native TSConfig base */
  "compilerOptions": {
    /* Visit https://aka.ms/tsconfig.json to read more about this file */

    /* Completeness */
    "skipLibCheck": true                                 /* Skip type checking all .d.ts files. */,
    "baseUrl": "./src",
    "paths": {
      "@/*": ["./*"],
    },
    "strictNullChecks": false,
    "noImplicitAny": false,
    "noUnusedLocals": true,
    "allowUmdGlobalAccess": true,
  },
  // "include": ["./src"],
  "exclude": [
    "node_modules",
    "babel.config.js",
    "metro.config.js",
  ]
}
`

**Comment by meimosor** [comment]
ctrl可以链接打开这个文件，但是会报这个错

**Comment by meimosor** [comment]
非常感谢，是缓存的问题

**Comment by onlyling** [comment]
> > 这个原因是因为 Android 多环境、渠道造成的，手动打开应用是不会有差别的。
> > 如果想一气呵成可以修改 `package.json` 里面 `android` 的命令，把 `--variant` 的值改为 `productionDebug`。
> > 在 `android/app/build.gradle` 文件的 `productFlavors ` 配置中对不同环境的 `applicationId` 添加了前缀，确保一个手机上可以同时安装多个环境的应用。如果开发中遇见 `applicationId` 的问题可以调整打包时的环境指定。
> 
> 修改后会有个问题，每次热更新后提示没有连接的APP，需要重新启动metro, 这样好麻烦，有什么办法吗？ ![image](https://user-images.githubusercontent.com/31975932/196154704-14e26b9f-2e63-47c0-8ecc-e543f7e76e73.png)

这个问题是你的开发机器和手机（模拟器）链接断开造成的，为什么断开了链接原因比较多，可能是数据线松动，可能是模拟器关闭后重新打开。
我们通常是「自定义  debug server host」直连开发机器 「IP:端口号(http://ip:8081)」，手动打开 App。
这样的错误提示并不会阻碍开发，debug 应用重新连接到一个 debug server  就恢复了。

**Comment by onlyling** [comment]
「使用cli生成项目后，启动找不到MainActivity」

可以修改 `scripts` 中的 `android` 为 `cross-env ENVFILE=.env.dev react-native run-android --variant 'devDebug' --appIdSuffix 'dev'`。

这里添加了 `--appIdSuffix 'dev'`，在 Android 开发机安装包后会自动启动/打开  xxx.xxx.dev 的包。`--variant` 的 dev 和 `--appIdSuffix` 的 dev 对应，其他值还有 `production`、`qa`、`demo`，对应是四种渠道（productFlavors）。
