### ISSUE TITLE
最新版的cli无法启动项目

### ISSUE THREAD

**Issue by meimosor** [hjfruit/react-native-lidong-template#4]
大佬，升级最新的cli后，启动报错了。
![image](https://user-images.githubusercontent.com/31975932/200209667-5cc08696-12e2-4d19-913d-1d042d2c1415.png)

**Comment by onlyling** [comment]
https://github.com/facebook/react-native/issues/35210

会不会是这个问题呢，升级一下 react native 版本。

**Comment by meimosor** [comment]
> [facebook/react-native#35210](https://github.com/facebook/react-native/issues/35210)
> 
> 会不会是这个问题呢，升级一下 react native 版本。

非常感谢，升级到0.70.5可以了
